import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.$executeRawUnsafe(`PRAGMA foreign_keys = ON;`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "Class" ("id" TEXT NOT NULL PRIMARY KEY, "name" TEXT NOT NULL UNIQUE, "description" TEXT NOT NULL DEFAULT '', "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "User" ("id" TEXT NOT NULL PRIMARY KEY, "username" TEXT NOT NULL UNIQUE, "passwordHash" TEXT NOT NULL, "nickname" TEXT NOT NULL, "role" TEXT NOT NULL DEFAULT 'USER', "enabled" BOOLEAN NOT NULL DEFAULT true, "classId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "User_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class" ("id") ON DELETE SET NULL ON UPDATE CASCADE);`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "Problem" ("id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "description" TEXT NOT NULL, "functionName" TEXT NOT NULL, "functionSig" TEXT NOT NULL, "codeTemplate" TEXT NOT NULL, "difficulty" TEXT NOT NULL DEFAULT 'Easy', "timeLimitMs" INTEGER NOT NULL DEFAULT 2000, "enabled" BOOLEAN NOT NULL DEFAULT true, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "TestCase" ("id" TEXT NOT NULL PRIMARY KEY, "problemId" TEXT NOT NULL, "args" TEXT NOT NULL, "expected" TEXT NOT NULL, "isSample" BOOLEAN NOT NULL DEFAULT false, "sortOrder" INTEGER NOT NULL DEFAULT 0, CONSTRAINT "TestCase_problemId_fkey" FOREIGN KEY ("problemId") REFERENCES "Problem" ("id") ON DELETE CASCADE ON UPDATE CASCADE);`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "ProblemAssignment" ("id" TEXT NOT NULL PRIMARY KEY, "problemId" TEXT NOT NULL, "classId" TEXT NOT NULL, CONSTRAINT "ProblemAssignment_problemId_fkey" FOREIGN KEY ("problemId") REFERENCES "Problem" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "ProblemAssignment_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class" ("id") ON DELETE CASCADE ON UPDATE CASCADE);`);
  await prisma.$executeRawUnsafe(`CREATE UNIQUE INDEX IF NOT EXISTS "ProblemAssignment_problemId_classId_key" ON "ProblemAssignment"("problemId", "classId");`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "Announcement" ("id" TEXT NOT NULL PRIMARY KEY, "title" TEXT NOT NULL, "body" TEXT NOT NULL, "classId" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "Announcement_classId_fkey" FOREIGN KEY ("classId") REFERENCES "Class" ("id") ON DELETE SET NULL ON UPDATE CASCADE);`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "Submission" ("id" TEXT NOT NULL PRIMARY KEY, "userId" TEXT NOT NULL, "problemId" TEXT NOT NULL, "code" TEXT NOT NULL, "status" TEXT NOT NULL DEFAULT 'PENDING', "score" INTEGER NOT NULL DEFAULT 0, "durationMs" INTEGER, "error" TEXT, "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, "completedAt" DATETIME, CONSTRAINT "Submission_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "Submission_problemId_fkey" FOREIGN KEY ("problemId") REFERENCES "Problem" ("id") ON DELETE CASCADE ON UPDATE CASCADE);`);
  await prisma.$executeRawUnsafe(`CREATE TABLE IF NOT EXISTS "SubmissionCaseResult" ("id" TEXT NOT NULL PRIMARY KEY, "submissionId" TEXT NOT NULL, "testCaseId" TEXT NOT NULL, "status" TEXT NOT NULL, "durationMs" INTEGER NOT NULL, "actual" TEXT, "error" TEXT, CONSTRAINT "SubmissionCaseResult_submissionId_fkey" FOREIGN KEY ("submissionId") REFERENCES "Submission" ("id") ON DELETE CASCADE ON UPDATE CASCADE, CONSTRAINT "SubmissionCaseResult_testCaseId_fkey" FOREIGN KEY ("testCaseId") REFERENCES "TestCase" ("id") ON DELETE CASCADE ON UPDATE CASCADE);`);
  console.log("SQLite tables are ready.");
}

main().finally(() => prisma.$disconnect());
